# Generated by Django 4.1.3 on 2022-11-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_subscribe"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
